// Frontend/E-Commerce/src/app/register/register.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CommunicationService } from '../services/communication.service';
import { HttpService } from '../services/http.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  imports: [ReactiveFormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})

export class RegisterComponent {
    registerForm: FormGroup = new FormGroup({
      fullName: new FormControl('', [Validators.required, Validators.minLength(2)]),
      email: new FormControl('', [Validators.required, Validators.email]),
      password: new FormControl('', [Validators.required, Validators.minLength(2)]),
      role: new FormControl('', [Validators.required]),
      preferences: new FormControl(''),
      vendorName: new FormControl(''),
      addressLine1: new FormControl('', [Validators.required]),
      city: new FormControl('', [Validators.required]),
      postalCode: new FormControl('', [Validators.required]),
      country: new FormControl('', [Validators.required])
    });
  errorMessage: string = '';

  constructor(private http: HttpService, private router: Router) { }

  
  onSubmit(): void {
    if (this.registerForm.invalid) {
      return;
    }

    this.errorMessage = '';

    const formData = this.registerForm.value;
    // Remove empty fields for non-selected role
    this.http.registerUser(formData).subscribe((data: any) => {
      console.log('Registration successful', data);
      this.router.navigate(['/login']);
    })


  }
}

<div class="register-wrapper">
  <div class="register-container">
    <h2>Create Account</h2>
    <p class="subtitle">Join our ecommerce platform</p>
    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="register-form">
      <div class="form-group">
        <label for="full_name" class="form-label">
          <i class="fas fa-user"></i> Full Name
        </label>
        <input
          type="text"
          id="full_name"
          formControlName="fullName"
          class="form-input"
          placeholder="Enter your full name"
        />
      </div>
      <div class="form-group">
        <label for="email" class="form-label">
          <i class="fas fa-envelope"></i> Email
        </label>
        <input
          type="email"
          id="email"
          formControlName="email"
          class="form-input"
          placeholder="Enter your email"
        />
      </div>
      <div class="form-group">
        <label for="password" class="form-label">
          <i class="fas fa-lock"></i> Password
        </label>
        <input
          type="password"
          id="password"
          formControlName="password"
          class="form-input"
          placeholder="Enter your password"
        />
      </div>
      <div class="form-group">
        <label for="role" class="form-label">
          <i class="fas fa-user-tag"></i> Role
        </label>
        <select id="role" formControlName="role" class="form-input">
          <option value="" disabled>Select your role</option>
          <option value="buyer">Buyer</option>
          <option value="vendor">Vendor</option>
        </select>
      </div>
      @if(registerForm.get('role')?.value === 'buyer')
      {<div class="form-group" >
        <label for="preferences" class="form-label">
          <i class="fas fa-heart"></i> Preferences
        </label>
        <input
          type="text"
          id="preferences"
          formControlName="preferences"
          class="form-input"
          placeholder="E.g., male, female, children, etc."
        />
      </div>}
      @if(registerForm.get('role')?.value === 'vendor')
      {
        <div class="form-group" >
        <label for="vendor_name" class="form-label">
          <i class="fas fa-store"></i> Vendor Name
        </label>
        <input
          type="text"
          id="vendor_name"
          formControlName="vendorName"
          class="form-input"
          placeholder="Enter your store name"
        />
      </div>}
      <div class="form-group">
        <label for="address_line1" class="form-label">
          <i class="fas fa-map-marker-alt"></i> Address Line 1
        </label>
        <input
          type="text"
          id="address_line1"
          formControlName="addressLine1"
          class="form-input"
          placeholder="Enter your address"
        />
      </div>
      <div class="form-group">
        <label for="city" class="form-label">
          <i class="fas fa-city"></i> City
        </label>
        <input
          type="text"
          id="city"
          formControlName="city"
          class="form-input"
          placeholder="Enter your city"
        />
      </div>
      <div class="form-group">
        <label for="postal_code" class="form-label">
          <i class="fas fa-mail-bulk"></i> Postal Code
        </label>
        <input
          type="text"
          id="postal_code"
          formControlName="postalCode"
          class="form-input"
          placeholder="Enter your postal code"
        />
      </div>
      <div class="form-group">
        <label for="country" class="form-label">
          <i class="fas fa-globe"></i> Country
        </label>
        <input
          type="text"
          id="country"
          formControlName="country"
          class="form-input"
          placeholder="Enter your country"
        />
      </div>
      <button
        type="submit"
        class="register-btn"
        [disabled]="registerForm.invalid"
      >
        Sign Up
      </button>
    </form>
    @if(errorMessage)
    {<p class="error-message" >{{ errorMessage }}</p>}
    <p class="login-link">
      Already have an account? <a href="/login">Sign in</a>
    </p>
  </div>
</div>

// client/src/pages/public/Register.tsx

import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { registerUser } from '@/services/api';
import { toast } from '@/components/ui/use-toast';
import { Button } from "@/components/ui/button";
import LoadingSpinner from '@/components/LoadingSpinner';

type FormData = {
  fullName: string;
  email: string;
  password: string;
  role: 'buyer' | 'vendor';
  preferences?: string;
  vendorName?: string;
  addressLine1: string;
  city: string;
  postalCode: string;
  country: string;
};

const Register: React.FC = () => {
  const { register, handleSubmit, watch, formState: { errors } } = useForm<FormData>();
  const navigate = useNavigate();
  const role = watch('role');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const onSubmit = async (data: FormData) => {
    setIsSubmitting(true);
    try {
      await registerUser(data);
      toast({
        title: 'Registration successful!',
        description: 'You can now login with your credentials.',
      });
      navigate('/login');
    } catch (error: any) {
      toast({
        title: 'Registration failed',
        description: error.response?.data?.message || 'Something went wrong',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="py-10">
      <div className="container mx-auto px-4">
        <div className="max-w-md mx-auto bg-white rounded-lg shadow-md overflow-hidden">
          <div className="py-4 px-6">
            <h2 className="text-2xl font-bold text-center text-gray-800 mb-6">Create Account</h2>
            
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
              <div>
                <label htmlFor="fullName" className="block text-sm font-medium text-gray-700">Full Name</label>
                <input
                  id="fullName"
                  type="text"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('fullName', { required: 'Full Name is required' })}
                />
                {errors.fullName && <p className="text-red-500 text-xs mt-1">{errors.fullName.message}</p>}
              </div>

              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
                <input
                  id="email"
                  type="email"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('email', { 
                    required: 'Email is required',
                    pattern: {
                      value: /^\S+@\S+$/i,
                      message: 'Invalid email format'
                    }
                  })}
                />
                {errors.email && <p className="text-red-500 text-xs mt-1">{errors.email.message}</p>}
              </div>

              <div>
                <label htmlFor="password" className="block text-sm font-medium text-gray-700">Password</label>
                <input
                  id="password"
                  type="password"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('password', { 
                    required: 'Password is required',
                    minLength: {
                      value: 8,
                      message: 'Password must be at least 8 characters'
                    }
                  })}
                />
                {errors.password && <p className="text-red-500 text-xs mt-1">{errors.password.message}</p>}
              </div>

              <div>
                <label htmlFor="role" className="block text-sm font-medium text-gray-700">Role</label>
                <select
                  id="role"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('role', { required: 'Role is required' })}
                >
                  <option value="">Select role</option>
                  <option value="buyer">Buyer</option>
                  <option value="vendor">Vendor</option>
                </select>
                {errors.role && <p className="text-red-500 text-xs mt-1">{errors.role.message}</p>}
              </div>

              {role === 'buyer' && (
                <div>
                  <label htmlFor="preferences" className="block text-sm font-medium text-gray-700">Preferences</label>
                  <select
                    id="preferences"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                    {...register('preferences', { required: 'Preferences is required for buyers' })}
                  >
                    <option value="">Select preference</option>
                    <option value="female">Female</option>
                    <option value="male">Male</option>
                    <option value="children">Children</option>
                  </select>
                  {errors.preferences && <p className="text-red-500 text-xs mt-1">{errors.preferences.message}</p>}
                </div>
              )}

              {role === 'vendor' && (
                <div>
                  <label htmlFor="vendorName" className="block text-sm font-medium text-gray-700">Vendor Name</label>
                  <input
                    id="vendorName"
                    type="text"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                    placeholder="Enter your store name"
                    {...register('vendorName', { required: 'Vendor name is required for vendors' })}
                  />
                  {errors.vendorName && <p className="text-red-500 text-xs mt-1">{errors.vendorName.message}</p>}
                </div>
              )}

              <div>
                <label htmlFor="addressLine1" className="block text-sm font-medium text-gray-700">Address</label>
                <input
                  id="addressLine1"
                  type="text"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('addressLine1', { required: 'Address is required' })}
                />
                {errors.addressLine1 && <p className="text-red-500 text-xs mt-1">{errors.addressLine1.message}</p>}
              </div>

              <div>
                <label htmlFor="city" className="block text-sm font-medium text-gray-700">City</label>
                <input
                  id="city"
                  type="text"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('city', { required: 'City is required' })}
                />
                {errors.city && <p className="text-red-500 text-xs mt-1">{errors.city.message}</p>}
              </div>

              <div>
                <label htmlFor="postalCode" className="block text-sm font-medium text-gray-700">Postal Code</label>
                <input
                  id="postalCode"
                  type="text"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('postalCode', { required: 'Postal Code is required' })}
                />
                {errors.postalCode && <p className="text-red-500 text-xs mt-1">{errors.postalCode.message}</p>}
              </div>

              <div>
                <label htmlFor="country" className="block text-sm font-medium text-gray-700">Country</label>
                <input
                  id="country"
                  type="text"
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border focus:border-brand focus:ring focus:ring-brand focus:ring-opacity-50"
                  {...register('country', { required: 'Country is required' })}
                />
                {errors.country && <p className="text-red-500 text-xs mt-1">{errors.country.message}</p>}
              </div>

              <Button type="submit" className="w-full" disabled={isSubmitting}>
                {isSubmitting ? <LoadingSpinner size="small" /> : 'Register'}
              </Button>

              <div className="text-center mt-4">
                <p className="text-sm text-gray-600">
                  Already have an account?{' '}
                  <Link to="/login" className="font-medium text-brand hover:underline">
                    Login
                  </Link>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
